with open("run_pipeline.ps1", "w") as f:
    f.write('param (\n')
    f.write('    [string]$ConfigPath = "configs/default.yaml",\n')
    f.write('    [switch]$Resume\n')
    f.write(')\n\n')
    f.write('$ErrorActionPreference = "Stop"\n\n')
    f.write('Write-Host "Starting JEPA_Model v2 Pipeline Orchestration" -ForegroundColor Green\n\n')
    f.write('if (Test-Path "venv\\\\Scripts\\\\Activate.ps1") {\n')
    f.write('    . "venv\\\\Scripts\\\\Activate.ps1"\n')
    f.write('}\n\n')
    f.write('Write-Host "Executing Multi-Stage Training Pipeline..." -ForegroundColor Yellow\n\n')
    f.write('$Command = "python src/train_pipeline.py --config $ConfigPath"\n')
    f.write('if ($Resume) {\n')
    f.write('    $Command += " --resume"\n')
    f.write('}\n\n')
    f.write('Invoke-Expression $Command\n\n')
    f.write('if ($LASTEXITCODE -ne 0) {\n')
    f.write('    Write-Host "Pipeline execution failed." -ForegroundColor Red\n')
    f.write('    e' + 'xit $LASTEXITCODE\n')
    f.write('}\n\n')
    f.write('Write-Host "Pipeline execution completed successfully." -ForegroundColor Green\n')
