import torch
from transformers import AutoTokenizer
import math

def validate_frontier_shard(distilled_file_path, tokenizer_id="Qwen/Qwen2.5-7B-Instruct"):
    print(f"[SYSTEM] Loading Tokenizer: {tokenizer_id}...")
    tokenizer = AutoTokenizer.from_pretrained(tokenizer_id, trust_remote_code=True)
    
    print(f"[SYSTEM] Loading Data Shard: {distilled_file_path}")
    data = torch.load(distilled_file_path, map_location="cpu", weights_only=True)
    
    input_tokens = data.get("input_tokens", [])
    qwen_tokens = data.get("qwen_tokens", [])
    target_concepts = data.get("target_concept", [])
    
    num_samples = min(3, len(input_tokens))
    print(f"\n--- Inspecting {num_samples} Samples from Frontier Data ---\n")
    
    for idx in range(num_samples):
        print(f"=== SAMPLE {idx} ===")
        
        # 1. Decode Prompt
        prompt_ids = input_tokens[idx].tolist()
        prompt_text = tokenizer.decode(prompt_ids, skip_special_tokens=True)
        print(f"👉 PROMPT ({len(prompt_ids)} tokens):\n{prompt_text[:300]}...\n")
        
        # 2. Decode Target Response
        gen_ids = qwen_tokens[idx].tolist()
        generated_text = tokenizer.decode(gen_ids, skip_special_tokens=True)
        print(f"🤖 FRONTIER RESPONSE ({len(gen_ids)} tokens):")
        print(f"{generated_text[:500]}... [TRUNCATED FOR DISPLAY]")
        print("-" * 50)
        
        # 3. Validate JEPA Concept Vector
        concept_vec = target_concepts[idx]
        vec_shape = list(concept_vec.shape)
        
        # Check L2 Normalization (Magnitude should be exactly 1.0)
        magnitude = torch.norm(concept_vec, p=2).item()
        is_normalized = math.isclose(magnitude, 1.0, rel_tol=1e-4)
        
        print("🧬 TARGET CONCEPT VECTOR:")
        print(f"Shape: {vec_shape} (Expected: [1024])")
        print(f"L2 Norm Magnitude: {magnitude:.4f} -> {'✅ NORMALIZED' if is_normalized else '❌ FAILED NORM'}")
        print("=" * 60 + "\n")

if __name__ == "__main__":
    # Point to your local shard path generated by extract_frontier_data.py
    validate_frontier_shard(r"F:\JEPA_Model\data\shards\frontier_claude_opus_chunk_0.pt")
